package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.ZcFaCardSub;
import com.ufgov.zc.common.sf.model.ZcFaCardSubExample;

public interface IZcFaCardSubDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int countByExample(ZcFaCardSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int deleteByExample(ZcFaCardSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int insert(ZcFaCardSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int insertSelective(ZcFaCardSub record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    List selectByExample(ZcFaCardSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int updateByExampleSelective(ZcFaCardSub record,ZcFaCardSubExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    int updateByExample( ZcFaCardSub record, ZcFaCardSubExample example);

    void insertList(List subList);

    void deleteByCardId(String cardId);
}