package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.ZcFaUsing;
import com.ufgov.zc.common.sf.model.ZcFaUsingExample;

public interface IZcFaUsingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int countByExample(ZcFaUsingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int deleteByExample(ZcFaUsingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int insert(ZcFaUsing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int insertSelective(ZcFaUsing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    List selectByExample(ZcFaUsingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int updateByExampleSelective(ZcFaUsing record, ZcFaUsingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    int updateByExample(ZcFaUsing record, ZcFaUsingExample example);

    void deleteByCardId(String cardId);

    void insertList(List usingList);
}