package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.ZcFaCard;
import com.ufgov.zc.common.sf.model.ZcFaCardExample;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface IZcFaCardDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int countByExample(ZcFaCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int deleteByExample(ZcFaCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int insert(ZcFaCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int insertSelective(ZcFaCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    List selectByExample(ZcFaCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int updateByExampleSelective(ZcFaCard record, ZcFaCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD
     *
     * @mbggenerated Wed Mar 05 03:55:50 CST 2014
     */
    int updateByExample(ZcFaCard record, ZcFaCardExample example);

    List getCardLst(ElementConditionDto elementConditionDto);
    
    ZcFaCard selectByCardId(String cardId);

    void update(ZcFaCard card);

    void deleteByCardIdFN(String cardId);
    
}