package com.ufgov.zc.server.sf.dao;

import java.util.List;

import com.ufgov.zc.common.sf.model.SfJdDocCode;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

public interface SfJdDocCodeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_DOC_CODE
	 * @mbggenerated  Sun Jul 17 14:24:21 CST 2016
	 */
	int deleteByPrimaryKey(String pinJieCode);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_DOC_CODE
	 * @mbggenerated  Sun Jul 17 14:24:21 CST 2016
	 */
	int insert(SfJdDocCode record);
 
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_DOC_CODE
	 * @mbggenerated  Sun Jul 17 14:24:21 CST 2016
	 */
	SfJdDocCode selectByPrimaryKey(String pinJieCode);
 
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SF_JD_DOC_CODE
	 * @mbggenerated  Sun Jul 17 14:24:21 CST 2016
	 */
	int updateByPrimaryKey(SfJdDocCode record);

    List getSfJdDocCodeLst(ElementConditionDto elementConditionDto);
}