package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfJdRecordFileModel;
import java.math.BigDecimal;

public interface SfJdRecordFileModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    int insert(SfJdRecordFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    int insertSelective(SfJdRecordFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    SfJdRecordFileModel selectByPrimaryKey(BigDecimal modelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    int updateByPrimaryKeySelective(SfJdRecordFileModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_RECORD_FILE_MODEL
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    int updateByPrimaryKey(SfJdRecordFileModel record);
}