package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfJdReport;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

import java.math.BigDecimal;
import java.util.List;

public interface SfJdReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_REPORT
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal jdReporId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_REPORT
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    int insert(SfJdReport record);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_REPORT
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    SfJdReport selectByPrimaryKey(BigDecimal jdReporId);
 
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JD_REPORT
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    int updateByPrimaryKey(SfJdReport record);

    
    List getMainDataLst(ElementConditionDto elementConditionDto);
}