package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfJdjg;
import java.math.BigDecimal;

public interface SfJdjgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal jgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    int insert(SfJdjg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    int insertSelective(SfJdjg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    SfJdjg selectByPrimaryKey(BigDecimal jgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    int updateByPrimaryKeySelective(SfJdjg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_JDJG
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    int updateByPrimaryKey(SfJdjg record);
}