package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfSjSupplier;
import com.ufgov.zc.common.system.dto.ElementConditionDto;

import java.math.BigDecimal;
import java.util.List;

public interface SfSjSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    int insert(SfSjSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    int insertSelective(SfSjSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    SfSjSupplier selectByPrimaryKey(BigDecimal supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    int updateByPrimaryKeySelective(SfSjSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ_SUPPLIER
     *
     * @mbggenerated Tue Aug 09 23:01:07 CST 2016
     */
    int updateByPrimaryKey(SfSjSupplier record);
    public List getMainLst(ElementConditionDto elementConditionDto) ;
}