package com.ufgov.zc.server.sf.dao;

import com.ufgov.zc.common.sf.model.SfSj;
import java.math.BigDecimal;

public interface SfSjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    int deleteByPrimaryKey(BigDecimal sjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    int insert(SfSj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    int insertSelective(SfSj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    SfSj selectByPrimaryKey(BigDecimal sjId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    int updateByPrimaryKeySelective(SfSj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SF_SJ
     *
     * @mbggenerated Wed Aug 10 01:41:15 CST 2016
     */
    int updateByPrimaryKey(SfSj record);
}