package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.Date;

public class SfEntrustManage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private BigDecimal manageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private BigDecimal entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private Date manageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String inputor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String manageType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public BigDecimal getManageId() {
        return manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @param manageId the value for SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageId(BigDecimal manageId) {
        this.manageId = manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @return the value of SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public BigDecimal getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @param entrustId the value for SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setEntrustId(BigDecimal entrustId) {
        this.entrustId = entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public Date getManageTime() {
        return manageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @param manageTime the value for SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageTime(Date manageTime) {
        this.manageTime = manageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.REASON
     *
     * @return the value of SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.REASON
     *
     * @param reason the value for SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @return the value of SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getInputor() {
        return inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @param inputor the value for SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setInputor(String inputor) {
        this.inputor = inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @return the value of SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @param inputDate the value for SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @param manageType the value for SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageType(String manageType) {
        this.manageType = manageType;
    }
}