package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ufgov.zc.common.util.EmpMeta;
import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfEntrustManage extends ZcBaseBill {
  /**
   * 
   */
  private static final long serialVersionUID = -7445947140316725322L;
  
  public static final String MANAGE_TYPE_DELAY="delay";//延期
  public static final String MANAGE_TYPE_OTHER="other";//其他
  public static final String MANAGE_TYPE_PAUSE="pause";//暂停
  public static final String MANAGE_TYPE_SHOULI="shouli";//受理
  public static final String MANAGE_TYPE_START="start";//启动
  public static final String MANAGE_TYPE_STOP="stop";//终止
  public static final String MANAGE_TYPE_WEITUO="weituo";//委托
  public static final String MANAGE_TYPE_WENSHUJIAOFU="wenshujiaofu";//发放鉴定意见书
  public static final String MANAGE_TYPE_ZHUANSONG="zhuansong";//转送其他鉴定中心

  
  public static final String SEQ_SF_ENTRUST_MANAGE_ID = "SEQ_SF_ENTRUST_MANAGE_ID";

  public static final String TAB_ID = "SfEntrustManage_Tab";

  /**
   * 搜索条件
   */
  public static final String SEARCH_ID = "SfEntrustManage_search";

  public static final String SF_VS_ENTRUST_MANAGE_TYPE = "SF_VS_ENTRUST_MANAGE_TYPE";
  
  public static final String COL_CO_CODE="SF_ENTRUST_MANAGE_CO_CODE"; // 鉴定机构代码
  public static final String COL_ENTRUST_ID="SF_ENTRUST_MANAGE_ENTRUST_ID"; // 委托ID
  public static final String COL_ENTRUST_CODE="SF_ENTRUST_MANAGE_ENTRUST_CODE"; // 委托编号
  public static final String COL_INPUTOR="SF_ENTRUST_MANAGE_INPUTOR"; // 录入人
  public static final String COL_INPUT_DATE="SF_ENTRUST_MANAGE_INPUT_DATE"; // 录入时间
  public static final String COL_MANAGE_CONTENT="SF_ENTRUST_MANAGE_MANAGE_CONTENT"; // 管理内容
  public static final String COL_MANAGE_ID="SF_ENTRUST_MANAGE_MANAGE_ID"; // 管理记录ID
  public static final String COL_MANAGE_TIME="SF_ENTRUST_MANAGE_MANAGE_TIME"; // 管理时间
  public static final String COL_MANAGE_TYPE="SF_ENTRUST_MANAGE_MANAGE_TYPE"; // 管理类别:暂停、终止、启动、完成
  public static final String COL_ND="SF_ENTRUST_MANAGE_ND"; // 年度
  public static final String COL_NEW_END_DATE="SF_ENTRUST_MANAGE_NEW_END_DATE"; // 调整后日期
  public static final String COL_OLD_END_DATE="SF_ENTRUST_MANAGE_OLD_END_DATE"; // 原预计完成日期
  public static final String COL_REASON="SF_ENTRUST_MANAGE_REASON"; // 管理原因
  public static final String COL_MANAGE_TYPE_TXT="SF_ENTRUST_MANAGE_MANAGE_TYPE_TXT"; // 管理类别文本

  private String manageTypeTxt;
  private SfEntrust entrust;

  private String entrustCode;
  private String managerContent;
  
  private Date oldEndDate;
  private Date newEndDate;
       
    public String getManagerContent() {
    return managerContent;
  }

  public void setManagerContent(String managerContent) {
    this.managerContent = managerContent;
  }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private BigDecimal manageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private BigDecimal entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private Date manageTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String inputor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    private String manageType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public BigDecimal getManageId() {
        return manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @param manageId the value for SF_ENTRUST_MANAGE.MANAGE_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageId(BigDecimal manageId) {
        this.manageId = manageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @return the value of SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public BigDecimal getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @param entrustId the value for SF_ENTRUST_MANAGE.ENTRUST_ID
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setEntrustId(BigDecimal entrustId) {
        this.entrustId = entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public Date getManageTime() {
        return manageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @param manageTime the value for SF_ENTRUST_MANAGE.MANAGE_TIME
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageTime(Date manageTime) {
        this.manageTime = manageTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.REASON
     *
     * @return the value of SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.REASON
     *
     * @param reason the value for SF_ENTRUST_MANAGE.REASON
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @return the value of SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getInputor() {
        return inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.INPUTOR
     *
     * @param inputor the value for SF_ENTRUST_MANAGE.INPUTOR
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setInputor(String inputor) {
        this.inputor = inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @return the value of SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @param inputDate the value for SF_ENTRUST_MANAGE.INPUT_DATE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @return the value of SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public String getManageType() {
        return manageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @param manageType the value for SF_ENTRUST_MANAGE.MANAGE_TYPE
     *
     * @mbggenerated Mon Aug 15 09:54:19 CST 2016
     */
    public void setManageType(String manageType) {
        this.manageType = manageType;
    }

    public Date getOldEndDate() {
      return oldEndDate;
    }

    public void setOldEndDate(Date oldEndDate) {
      this.oldEndDate = oldEndDate;
    }

    public Date getNewEndDate() {
      return newEndDate;
    }

    public void setNewEndDate(Date newEndDate) {
      this.newEndDate = newEndDate;
    }

    public String getEntrustCode() {
      return entrustCode;
    }

    public void setEntrustCode(String entrustCode) {
      this.entrustCode = entrustCode;
    }
    public String getInputorName() {
      if(getInputor()!=null){
        return EmpMeta.getEmpName(getInputor());
      }
      return inputorName;

    }

    public SfEntrust getEntrust() {
      return entrust;
    }

    public void setEntrust(SfEntrust entrust) {
      this.entrust = entrust;
    }

    public String getManageTypeTxt() {
     /* if(getManageType()!=null){
        return AsValDataCache.getName(SfEntrustManage.SF_VS_ENTRUST_MANAGE_TYPE, getManageType());
      }*/
      return manageTypeTxt;
    }

    public void setManageTypeTxt(String manageTypeTxt) {
      this.manageTypeTxt = manageTypeTxt;
    }
}