package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfJdRecordFileModel extends ZcBaseBill {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3860327597420182539L;
	public static final String COL_CO_CODE="SF_JD_RECORD_FILE_MODEL_CO_CODE"; // 单位编号
	public static final String COL_DESCRIPTION="SF_JD_RECORD_FILE_MODEL_DESCRIPTION"; // 描述
	public static final String COL_FILE_ID="SF_JD_RECORD_FILE_MODEL_FILE_ID"; // 文件ID
	public static final String COL_FILE_NAME="SF_JD_RECORD_FILE_MODEL_FILE_NAME"; // 文件名
	public static final String COL_FILE_TYPE="SF_JD_RECORD_FILE_MODEL_FILE_TYPE"; // 文件类型
	public static final String COL_INPUTOR="SF_JD_RECORD_FILE_MODEL_INPUTOR"; // 录入人
	public static final String COL_INPUT_DATE="SF_JD_RECORD_FILE_MODEL_INPUT_DATE"; // 录入时间
	public static final String COL_IS_ENABLE="SF_JD_RECORD_FILE_MODEL_IS_ENABLE"; // 是否启用
	public static final String COL_MAJOR_CODE="SF_JD_RECORD_FILE_MODEL_MAJOR_CODE"; // 专业编号
	public static final String COL_MODEL_ID="SF_JD_RECORD_FILE_MODEL_MODEL_ID"; // 模板ID
	public static final String COL_NAME="SF_JD_RECORD_FILE_MODEL_NAME"; // 名称
	public static final String COL_ND="SF_JD_RECORD_FILE_MODEL_ND"; // 年度
	public static final String COL_REMARK="SF_JD_RECORD_FILE_MODEL_REMARK"; // 备注

	public static final String SF_VS_JD_FILE_MODEL_STATUS="SF_VS_JD_FILE_MODEL_STATUS";
	public static final String SF_VS_JD_FILE_MODEL_STATUS_enable="enable";
	public static final String SF_VS_JD_FILE_MODEL_STATUS_disable="disable";
	
	public static final String SF_VS_JD_FILE_MODEL_TYPE="SF_VS_JD_FILE_MODEL_TYPE";
	public static final String SF_VS_JD_FILE_MODEL_TYPE_word="word";
	public static final String SF_VS_JD_FILE_MODEL_TYPE_excel="excel";
	

	/**
	 *  文书类别：record 鉴定记录   report 鉴定意见书/鉴定报告
	 */
	public static final String SF_VS_JD_FILE_MODEL_DOC_TYPE="SF_VS_JD_FILE_MODEL_DOC_TYPE";
	public static final String SF_VS_JD_FILE_MODEL_DOC_TYPE_RECORD="record";// 文书类别：record 鉴定记录  
	public static final String SF_VS_JD_FILE_MODEL_DOC_TYPE_REPORT="report";// 文书类别： report 鉴定意见书/鉴定报告
	

	 


	  public final static String TAB_ID_SF_JD_RECORD_FILE_MODEL = "SfJdRecordFileModel_Tab";
	  

	  public static final String SEQ_SF_RECORD_FILE_MODEL_ID = "SEQ_SF_RECORD_FILE_MODEL_ID";
	  
	  /**
	   * 文书类别：record 鉴定记录   report 鉴定意见书/鉴定报告
	   */
	  private String docType;
	  
	  /**
	   * 鉴定意见书/鉴定报告类别
	   */
	  private String reportType;
	  
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.MODEL_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private BigDecimal modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.MAJOR_CODE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String majorCode;
 
 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.INPUTOR
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String inputor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.REMARK
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.DESCRIPTION
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.FILE_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String fileId;
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.FILE_TYPE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.NAME
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_FILE_MODEL.IS_ENABLE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    private String isEnable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.MODEL_ID
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.MODEL_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public BigDecimal getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.MODEL_ID
     *
     * @param modelId the value for SF_JD_RECORD_FILE_MODEL.MODEL_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setModelId(BigDecimal modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.MAJOR_CODE
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.MAJOR_CODE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.MAJOR_CODE
     *
     * @param majorCode the value for SF_JD_RECORD_FILE_MODEL.MAJOR_CODE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode;
    }
 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.INPUT_DATE
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.INPUT_DATE
     *
     * @param inputDate the value for SF_JD_RECORD_FILE_MODEL.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.INPUTOR
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.INPUTOR
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getInputor() {
        return inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.INPUTOR
     *
     * @param inputor the value for SF_JD_RECORD_FILE_MODEL.INPUTOR
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setInputor(String inputor) {
        this.inputor = inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.REMARK
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.REMARK
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.REMARK
     *
     * @param remark the value for SF_JD_RECORD_FILE_MODEL.REMARK
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.DESCRIPTION
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.DESCRIPTION
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.DESCRIPTION
     *
     * @param description the value for SF_JD_RECORD_FILE_MODEL.DESCRIPTION
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.FILE_ID
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.FILE_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.FILE_ID
     *
     * @param fileId the value for SF_JD_RECORD_FILE_MODEL.FILE_ID
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.FILE_TYPE
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.FILE_TYPE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.FILE_TYPE
     *
     * @param fileType the value for SF_JD_RECORD_FILE_MODEL.FILE_TYPE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.NAME
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.NAME
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.NAME
     *
     * @param name the value for SF_JD_RECORD_FILE_MODEL.NAME
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_FILE_MODEL.IS_ENABLE
     *
     * @return the value of SF_JD_RECORD_FILE_MODEL.IS_ENABLE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public String getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_FILE_MODEL.IS_ENABLE
     *
     * @param isEnable the value for SF_JD_RECORD_FILE_MODEL.IS_ENABLE
     *
     * @mbggenerated Sun Jul 17 18:09:27 CST 2016
     */
    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getDocType() {
		return docType;
	}

	public void setDocType(String docType) {
		this.docType = docType;
	}

	public String getReportType() {
		return reportType;
	}

	public void setReportType(String reportType) {
		this.reportType = reportType;
	}
}