package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.Date;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfJdReport extends ZcBaseBill {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 3224074338937464893L;
	
	public static final String SEQ_SF_JD_REPORT_ID="SEQ_SF_JD_REPORT_ID";
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.JD_REPOR_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private BigDecimal jdReporId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.JD_RESULT_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private BigDecimal jdResultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.ENTRUST_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private BigDecimal entrustId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.JD_REPORT_FILE_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private String jdReportFileId;
 
 
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.INPUTOR
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private String inputor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.STATUS
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.REMARK
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.PUBLISH_TIME
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_REPORT.REPORT_CODE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    private String reportCode;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.JD_REPOR_ID
     *
     * @return the value of SF_JD_REPORT.JD_REPOR_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public BigDecimal getJdReporId() {
        return jdReporId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.JD_REPOR_ID
     *
     * @param jdReporId the value for SF_JD_REPORT.JD_REPOR_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setJdReporId(BigDecimal jdReporId) {
        this.jdReporId = jdReporId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.JD_RESULT_ID
     *
     * @return the value of SF_JD_REPORT.JD_RESULT_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public BigDecimal getJdResultId() {
        return jdResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.JD_RESULT_ID
     *
     * @param jdResultId the value for SF_JD_REPORT.JD_RESULT_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setJdResultId(BigDecimal jdResultId) {
        this.jdResultId = jdResultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.ENTRUST_ID
     *
     * @return the value of SF_JD_REPORT.ENTRUST_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public BigDecimal getEntrustId() {
        return entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.ENTRUST_ID
     *
     * @param entrustId the value for SF_JD_REPORT.ENTRUST_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setEntrustId(BigDecimal entrustId) {
        this.entrustId = entrustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.JD_REPORT_FILE_ID
     *
     * @return the value of SF_JD_REPORT.JD_REPORT_FILE_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public String getJdReportFileId() {
        return jdReportFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.JD_REPORT_FILE_ID
     *
     * @param jdReportFileId the value for SF_JD_REPORT.JD_REPORT_FILE_ID
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setJdReportFileId(String jdReportFileId) {
        this.jdReportFileId = jdReportFileId;
    }

     

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.INPUTOR
     *
     * @return the value of SF_JD_REPORT.INPUTOR
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public String getInputor() {
        return inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.INPUTOR
     *
     * @param inputor the value for SF_JD_REPORT.INPUTOR
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setInputor(String inputor) {
        this.inputor = inputor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.INPUT_DATE
     *
     * @return the value of SF_JD_REPORT.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.INPUT_DATE
     *
     * @param inputDate the value for SF_JD_REPORT.INPUT_DATE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.STATUS
     *
     * @return the value of SF_JD_REPORT.STATUS
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.STATUS
     *
     * @param status the value for SF_JD_REPORT.STATUS
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.REMARK
     *
     * @return the value of SF_JD_REPORT.REMARK
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.REMARK
     *
     * @param remark the value for SF_JD_REPORT.REMARK
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.PUBLISH_TIME
     *
     * @return the value of SF_JD_REPORT.PUBLISH_TIME
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.PUBLISH_TIME
     *
     * @param publishTime the value for SF_JD_REPORT.PUBLISH_TIME
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_REPORT.REPORT_CODE
     *
     * @return the value of SF_JD_REPORT.REPORT_CODE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public String getReportCode() {
        return reportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_REPORT.REPORT_CODE
     *
     * @param reportCode the value for SF_JD_REPORT.REPORT_CODE
     *
     * @mbggenerated Sun Jul 17 16:30:58 CST 2016
     */
    public void setReportCode(String reportCode) {
        this.reportCode = reportCode;
    }

   
}