package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfJdDocCode extends ZcBaseBill {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -8891830353343795428L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_DOC_CODE.GONG_ZI
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    private String gongZi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_DOC_CODE.JIAN_ZI_1
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    private String jianZi1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_DOC_CODE.JIAN_ZI_2
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    private String jianZi2;
 

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_DOC_CODE.NUM
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_DOC_CODE.PIN_JIE_CODE
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    private String pinJieCode;

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_DOC_CODE.GONG_ZI
     *
     * @return the value of SF_JD_DOC_CODE.GONG_ZI
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public String getGongZi() {
        return gongZi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_DOC_CODE.GONG_ZI
     *
     * @param gongZi the value for SF_JD_DOC_CODE.GONG_ZI
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public void setGongZi(String gongZi) {
        this.gongZi = gongZi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_DOC_CODE.JIAN_ZI_1
     *
     * @return the value of SF_JD_DOC_CODE.JIAN_ZI_1
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public String getJianZi1() {
        return jianZi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_DOC_CODE.JIAN_ZI_1
     *
     * @param jianZi1 the value for SF_JD_DOC_CODE.JIAN_ZI_1
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public void setJianZi1(String jianZi1) {
        this.jianZi1 = jianZi1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_DOC_CODE.JIAN_ZI_2
     *
     * @return the value of SF_JD_DOC_CODE.JIAN_ZI_2
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public String getJianZi2() {
        return jianZi2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_DOC_CODE.JIAN_ZI_2
     *
     * @param jianZi2 the value for SF_JD_DOC_CODE.JIAN_ZI_2
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public void setJianZi2(String jianZi2) {
        this.jianZi2 = jianZi2;
    }

 

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_DOC_CODE.NUM
     *
     * @return the value of SF_JD_DOC_CODE.NUM
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_DOC_CODE.NUM
     *
     * @param num the value for SF_JD_DOC_CODE.NUM
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_DOC_CODE.PIN_JIE_CODE
     *
     * @return the value of SF_JD_DOC_CODE.PIN_JIE_CODE
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public String getPinJieCode() {
        return pinJieCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_DOC_CODE.PIN_JIE_CODE
     *
     * @param pinJieCode the value for SF_JD_DOC_CODE.PIN_JIE_CODE
     *
     * @mbggenerated Sun Jul 17 14:07:37 CST 2016
     */
    public void setPinJieCode(String pinJieCode) {
        this.pinJieCode = pinJieCode;
    }
}