package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfJdjg extends ZcBaseBill{
	
	public static final String SEQ_SF_JDJG_ID="SEQ_SF_JDJG_ID";
	
	public static final String TAB_ID="SfJdjgt_Tab";
	
	public static final String COL_ADDRESS="SF_JDJG_ADDRESS"; // 地址
	public static final String COL_CO_CODE="SF_JDJG_CO_CODE"; // 单位编码
	public static final String COL_FAX="SF_JDJG_FAX"; // 传真
	public static final String COL_JG_ID="SF_JDJG_JG_ID"; // 机构ID
	public static final String COL_LINK_MAN="SF_JDJG_LINK_MAN"; // 联系人
	public static final String COL_NAME="SF_JDJG_NAME"; // 机构名称
	public static final String COL_TEL="SF_JDJG_TEL"; // 电话
	public static final String COL_XKZH="SF_JDJG_XKZH"; // 许可证号
	public static final String COL_ZIP="SF_JDJG_ZIP"; // 邮编
	public static final String COL_EN_NAME="SF_JDJG_EN_NAME"; // 英文名称
  public static final String COL_SHORT_NAME="SF_JDJG_SHORT_NAME"; // 简称
   
  public static final String SF_VS_JDJG = "SF_VS_JDJG";


	  private List certificatLst=new ArrayList();
	  
	  private String shortName;
	  
	  private String enName;
	
    /**
     * 
     * 
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.JG_ID
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private BigDecimal jgId;

     

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.NAME
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.XKZH
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String xkzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.TEL
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.LINK_MAN
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String linkMan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.ADDRESS
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.ZIP
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JDJG.FAX
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    private String fax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.JG_ID
     *
     * @return the value of SF_JDJG.JG_ID
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public BigDecimal getJgId() {
        return jgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.JG_ID
     *
     * @param jgId the value for SF_JDJG.JG_ID
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setJgId(BigDecimal jgId) {
        this.jgId = jgId;
    }

    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.NAME
     *
     * @return the value of SF_JDJG.NAME
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.NAME
     *
     * @param name the value for SF_JDJG.NAME
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.XKZH
     *
     * @return the value of SF_JDJG.XKZH
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getXkzh() {
        return xkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.XKZH
     *
     * @param xkzh the value for SF_JDJG.XKZH
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setXkzh(String xkzh) {
        this.xkzh = xkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.TEL
     *
     * @return the value of SF_JDJG.TEL
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.TEL
     *
     * @param tel the value for SF_JDJG.TEL
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.LINK_MAN
     *
     * @return the value of SF_JDJG.LINK_MAN
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.LINK_MAN
     *
     * @param linkMan the value for SF_JDJG.LINK_MAN
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.ADDRESS
     *
     * @return the value of SF_JDJG.ADDRESS
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.ADDRESS
     *
     * @param address the value for SF_JDJG.ADDRESS
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.ZIP
     *
     * @return the value of SF_JDJG.ZIP
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.ZIP
     *
     * @param zip the value for SF_JDJG.ZIP
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JDJG.FAX
     *
     * @return the value of SF_JDJG.FAX
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JDJG.FAX
     *
     * @param fax the value for SF_JDJG.FAX
     *
     * @mbggenerated Thu Jul 28 15:56:39 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

	public List getCertificatLst() {
		return certificatLst;
	}

	public void setCertificatLst(List certificatLst) {
		this.certificatLst = certificatLst;
	}

	public String getEnName() {
		return enName;
	}

	public void setEnName(String enName) {
		this.enName = enName;
	}

  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }
}