package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class SfJdRecordModel extends ZcBaseBill{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.JD_RECORD_MODEL_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private BigDecimal jdRecordModelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.MAJOR_CODE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String majorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.JD_PERSON_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String jdPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.SUMMARY
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.IS_PUBLIC
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String isPublic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.FILE_NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.FILE_BLOB_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String fileBlobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.MODEL_TYPE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String modelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SF_JD_RECORD_MODEL.CONTENT
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.JD_RECORD_MODEL_ID
     *
     * @return the value of SF_JD_RECORD_MODEL.JD_RECORD_MODEL_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public BigDecimal getJdRecordModelId() {
        return jdRecordModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.JD_RECORD_MODEL_ID
     *
     * @param jdRecordModelId the value for SF_JD_RECORD_MODEL.JD_RECORD_MODEL_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setJdRecordModelId(BigDecimal jdRecordModelId) {
        this.jdRecordModelId = jdRecordModelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.MAJOR_CODE
     *
     * @return the value of SF_JD_RECORD_MODEL.MAJOR_CODE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getMajorCode() {
        return majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.MAJOR_CODE
     *
     * @param majorCode the value for SF_JD_RECORD_MODEL.MAJOR_CODE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setMajorCode(String majorCode) {
        this.majorCode = majorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.JD_PERSON_ID
     *
     * @return the value of SF_JD_RECORD_MODEL.JD_PERSON_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getJdPersonId() {
        return jdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.JD_PERSON_ID
     *
     * @param jdPersonId the value for SF_JD_RECORD_MODEL.JD_PERSON_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setJdPersonId(String jdPersonId) {
        this.jdPersonId = jdPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.NAME
     *
     * @return the value of SF_JD_RECORD_MODEL.NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.NAME
     *
     * @param name the value for SF_JD_RECORD_MODEL.NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.SUMMARY
     *
     * @return the value of SF_JD_RECORD_MODEL.SUMMARY
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.SUMMARY
     *
     * @param summary the value for SF_JD_RECORD_MODEL.SUMMARY
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.IS_PUBLIC
     *
     * @return the value of SF_JD_RECORD_MODEL.IS_PUBLIC
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getIsPublic() {
        return isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.IS_PUBLIC
     *
     * @param isPublic the value for SF_JD_RECORD_MODEL.IS_PUBLIC
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setIsPublic(String isPublic) {
        this.isPublic = isPublic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.FILE_NAME
     *
     * @return the value of SF_JD_RECORD_MODEL.FILE_NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.FILE_NAME
     *
     * @param fileName the value for SF_JD_RECORD_MODEL.FILE_NAME
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.FILE_BLOB_ID
     *
     * @return the value of SF_JD_RECORD_MODEL.FILE_BLOB_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getFileBlobId() {
        return fileBlobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.FILE_BLOB_ID
     *
     * @param fileBlobId the value for SF_JD_RECORD_MODEL.FILE_BLOB_ID
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setFileBlobId(String fileBlobId) {
        this.fileBlobId = fileBlobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.MODEL_TYPE
     *
     * @return the value of SF_JD_RECORD_MODEL.MODEL_TYPE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getModelType() {
        return modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.MODEL_TYPE
     *
     * @param modelType the value for SF_JD_RECORD_MODEL.MODEL_TYPE
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setModelType(String modelType) {
        this.modelType = modelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SF_JD_RECORD_MODEL.CONTENT
     *
     * @return the value of SF_JD_RECORD_MODEL.CONTENT
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SF_JD_RECORD_MODEL.CONTENT
     *
     * @param content the value for SF_JD_RECORD_MODEL.CONTENT
     *
     * @mbggenerated Mon Jul 18 13:02:17 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}