package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ZcFaUsingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public ZcFaUsingExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List getAllCriteria() {
            return criteria;
        }

        public List getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardIdIsNull() {
            addCriterion("CARD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("CARD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("CARD_ID =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("CARD_ID <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("CARD_ID >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_ID >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("CARD_ID <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_ID <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("CARD_ID like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("CARD_ID not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List values) {
            addCriterion("CARD_ID in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List values) {
            addCriterion("CARD_ID not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("CARD_ID between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("CARD_ID not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("ORG_CODE =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("ORG_CODE <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("ORG_CODE >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CODE >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("ORG_CODE <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("ORG_CODE <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("ORG_CODE like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("ORG_CODE not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List values) {
            addCriterion("ORG_CODE in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List values) {
            addCriterion("ORG_CODE not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("ORG_CODE between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("ORG_CODE not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andUseRatIsNull() {
            addCriterion("USE_RAT is null");
            return (Criteria) this;
        }

        public Criteria andUseRatIsNotNull() {
            addCriterion("USE_RAT is not null");
            return (Criteria) this;
        }

        public Criteria andUseRatEqualTo(BigDecimal value) {
            addCriterion("USE_RAT =", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatNotEqualTo(BigDecimal value) {
            addCriterion("USE_RAT <>", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatGreaterThan(BigDecimal value) {
            addCriterion("USE_RAT >", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USE_RAT >=", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatLessThan(BigDecimal value) {
            addCriterion("USE_RAT <", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USE_RAT <=", value, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatIn(List values) {
            addCriterion("USE_RAT in", values, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatNotIn(List values) {
            addCriterion("USE_RAT not in", values, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USE_RAT between", value1, value2, "useRat");
            return (Criteria) this;
        }

        public Criteria andUseRatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USE_RAT not between", value1, value2, "useRat");
            return (Criteria) this;
        }

        public Criteria andSerialIsNull() {
            addCriterion("SERIAL is null");
            return (Criteria) this;
        }

        public Criteria andSerialIsNotNull() {
            addCriterion("SERIAL is not null");
            return (Criteria) this;
        }

        public Criteria andSerialEqualTo(String value) {
            addCriterion("SERIAL =", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotEqualTo(String value) {
            addCriterion("SERIAL <>", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThan(String value) {
            addCriterion("SERIAL >", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThanOrEqualTo(String value) {
            addCriterion("SERIAL >=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThan(String value) {
            addCriterion("SERIAL <", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThanOrEqualTo(String value) {
            addCriterion("SERIAL <=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLike(String value) {
            addCriterion("SERIAL like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotLike(String value) {
            addCriterion("SERIAL not like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialIn(List values) {
            addCriterion("SERIAL in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotIn(List values) {
            addCriterion("SERIAL not in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialBetween(String value1, String value2) {
            addCriterion("SERIAL between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotBetween(String value1, String value2) {
            addCriterion("SERIAL not between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameIsNull() {
            addCriterion("USE_EMP_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameIsNotNull() {
            addCriterion("USE_EMP_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameEqualTo(String value) {
            addCriterion("USE_EMP_NAME =", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameNotEqualTo(String value) {
            addCriterion("USE_EMP_NAME <>", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameGreaterThan(String value) {
            addCriterion("USE_EMP_NAME >", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("USE_EMP_NAME >=", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameLessThan(String value) {
            addCriterion("USE_EMP_NAME <", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameLessThanOrEqualTo(String value) {
            addCriterion("USE_EMP_NAME <=", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameLike(String value) {
            addCriterion("USE_EMP_NAME like", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameNotLike(String value) {
            addCriterion("USE_EMP_NAME not like", value, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameIn(List values) {
            addCriterion("USE_EMP_NAME in", values, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameNotIn(List values) {
            addCriterion("USE_EMP_NAME not in", values, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameBetween(String value1, String value2) {
            addCriterion("USE_EMP_NAME between", value1, value2, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andUseEmpNameNotBetween(String value1, String value2) {
            addCriterion("USE_EMP_NAME not between", value1, value2, "useEmpName");
            return (Criteria) this;
        }

        public Criteria andNdIsNull() {
            addCriterion("ND is null");
            return (Criteria) this;
        }

        public Criteria andNdIsNotNull() {
            addCriterion("ND is not null");
            return (Criteria) this;
        }

        public Criteria andNdEqualTo(Long value) {
            addCriterion("ND =", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdNotEqualTo(Long value) {
            addCriterion("ND <>", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdGreaterThan(Long value) {
            addCriterion("ND >", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdGreaterThanOrEqualTo(Long value) {
            addCriterion("ND >=", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdLessThan(Long value) {
            addCriterion("ND <", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdLessThanOrEqualTo(Long value) {
            addCriterion("ND <=", value, "nd");
            return (Criteria) this;
        }

        public Criteria andNdIn(List values) {
            addCriterion("ND in", values, "nd");
            return (Criteria) this;
        }

        public Criteria andNdNotIn(List values) {
            addCriterion("ND not in", values, "nd");
            return (Criteria) this;
        }

        public Criteria andNdBetween(Long value1, Long value2) {
            addCriterion("ND between", value1, value2, "nd");
            return (Criteria) this;
        }

        public Criteria andNdNotBetween(Long value1, Long value2) {
            addCriterion("ND not between", value1, value2, "nd");
            return (Criteria) this;
        }

        public Criteria andCoCodeIsNull() {
            addCriterion("CO_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCoCodeIsNotNull() {
            addCriterion("CO_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCoCodeEqualTo(String value) {
            addCriterion("CO_CODE =", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeNotEqualTo(String value) {
            addCriterion("CO_CODE <>", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeGreaterThan(String value) {
            addCriterion("CO_CODE >", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CO_CODE >=", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeLessThan(String value) {
            addCriterion("CO_CODE <", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeLessThanOrEqualTo(String value) {
            addCriterion("CO_CODE <=", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeLike(String value) {
            addCriterion("CO_CODE like", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeNotLike(String value) {
            addCriterion("CO_CODE not like", value, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeIn(List values) {
            addCriterion("CO_CODE in", values, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeNotIn(List values) {
            addCriterion("CO_CODE not in", values, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeBetween(String value1, String value2) {
            addCriterion("CO_CODE between", value1, value2, "coCode");
            return (Criteria) this;
        }

        public Criteria andCoCodeNotBetween(String value1, String value2) {
            addCriterion("CO_CODE not between", value1, value2, "coCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeIsNull() {
            addCriterion("USE_EMP_CODE is null");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeIsNotNull() {
            addCriterion("USE_EMP_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeEqualTo(String value) {
            addCriterion("USE_EMP_CODE =", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeNotEqualTo(String value) {
            addCriterion("USE_EMP_CODE <>", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeGreaterThan(String value) {
            addCriterion("USE_EMP_CODE >", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeGreaterThanOrEqualTo(String value) {
            addCriterion("USE_EMP_CODE >=", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeLessThan(String value) {
            addCriterion("USE_EMP_CODE <", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeLessThanOrEqualTo(String value) {
            addCriterion("USE_EMP_CODE <=", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeLike(String value) {
            addCriterion("USE_EMP_CODE like", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeNotLike(String value) {
            addCriterion("USE_EMP_CODE not like", value, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeIn(List values) {
            addCriterion("USE_EMP_CODE in", values, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeNotIn(List values) {
            addCriterion("USE_EMP_CODE not in", values, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeBetween(String value1, String value2) {
            addCriterion("USE_EMP_CODE between", value1, value2, "useEmpCode");
            return (Criteria) this;
        }

        public Criteria andUseEmpCodeNotBetween(String value1, String value2) {
            addCriterion("USE_EMP_CODE not between", value1, value2, "useEmpCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 05 09:37:00 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_USING
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}