package com.ufgov.zc.common.sf.model;

import java.util.ArrayList;
import java.util.List;

public class ZcFaCardDocExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public ZcFaCardDocExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List getAllCriteria() {
            return criteria;
        }

        public List getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCardIdIsNull() {
            addCriterion("CARD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("CARD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("CARD_ID =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("CARD_ID <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("CARD_ID >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_ID >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("CARD_ID <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_ID <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("CARD_ID like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("CARD_ID not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List values) {
            addCriterion("CARD_ID in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List values) {
            addCriterion("CARD_ID not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("CARD_ID between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("CARD_ID not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardDocListIsNull() {
            addCriterion("CARD_DOC_LIST is null");
            return (Criteria) this;
        }

        public Criteria andCardDocListIsNotNull() {
            addCriterion("CARD_DOC_LIST is not null");
            return (Criteria) this;
        }

        public Criteria andCardDocListEqualTo(String value) {
            addCriterion("CARD_DOC_LIST =", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListNotEqualTo(String value) {
            addCriterion("CARD_DOC_LIST <>", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListGreaterThan(String value) {
            addCriterion("CARD_DOC_LIST >", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_LIST >=", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListLessThan(String value) {
            addCriterion("CARD_DOC_LIST <", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListLessThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_LIST <=", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListLike(String value) {
            addCriterion("CARD_DOC_LIST like", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListNotLike(String value) {
            addCriterion("CARD_DOC_LIST not like", value, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListIn(List values) {
            addCriterion("CARD_DOC_LIST in", values, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListNotIn(List values) {
            addCriterion("CARD_DOC_LIST not in", values, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListBetween(String value1, String value2) {
            addCriterion("CARD_DOC_LIST between", value1, value2, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocListNotBetween(String value1, String value2) {
            addCriterion("CARD_DOC_LIST not between", value1, value2, "cardDocList");
            return (Criteria) this;
        }

        public Criteria andCardDocIsNull() {
            addCriterion("CARD_DOC is null");
            return (Criteria) this;
        }

        public Criteria andCardDocIsNotNull() {
            addCriterion("CARD_DOC is not null");
            return (Criteria) this;
        }

        public Criteria andCardDocEqualTo(String value) {
            addCriterion("CARD_DOC =", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocNotEqualTo(String value) {
            addCriterion("CARD_DOC <>", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocGreaterThan(String value) {
            addCriterion("CARD_DOC >", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_DOC >=", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocLessThan(String value) {
            addCriterion("CARD_DOC <", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocLessThanOrEqualTo(String value) {
            addCriterion("CARD_DOC <=", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocLike(String value) {
            addCriterion("CARD_DOC like", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocNotLike(String value) {
            addCriterion("CARD_DOC not like", value, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocIn(List values) {
            addCriterion("CARD_DOC in", values, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocNotIn(List values) {
            addCriterion("CARD_DOC not in", values, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocBetween(String value1, String value2) {
            addCriterion("CARD_DOC between", value1, value2, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocNotBetween(String value1, String value2) {
            addCriterion("CARD_DOC not between", value1, value2, "cardDoc");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidIsNull() {
            addCriterion("CARD_DOC_BLOBID is null");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidIsNotNull() {
            addCriterion("CARD_DOC_BLOBID is not null");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidEqualTo(String value) {
            addCriterion("CARD_DOC_BLOBID =", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidNotEqualTo(String value) {
            addCriterion("CARD_DOC_BLOBID <>", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidGreaterThan(String value) {
            addCriterion("CARD_DOC_BLOBID >", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_BLOBID >=", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidLessThan(String value) {
            addCriterion("CARD_DOC_BLOBID <", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidLessThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_BLOBID <=", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidLike(String value) {
            addCriterion("CARD_DOC_BLOBID like", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidNotLike(String value) {
            addCriterion("CARD_DOC_BLOBID not like", value, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidIn(List values) {
            addCriterion("CARD_DOC_BLOBID in", values, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidNotIn(List values) {
            addCriterion("CARD_DOC_BLOBID not in", values, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidBetween(String value1, String value2) {
            addCriterion("CARD_DOC_BLOBID between", value1, value2, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocBlobidNotBetween(String value1, String value2) {
            addCriterion("CARD_DOC_BLOBID not between", value1, value2, "cardDocBlobid");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpIsNull() {
            addCriterion("CARD_DOC_PURP is null");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpIsNotNull() {
            addCriterion("CARD_DOC_PURP is not null");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpEqualTo(String value) {
            addCriterion("CARD_DOC_PURP =", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpNotEqualTo(String value) {
            addCriterion("CARD_DOC_PURP <>", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpGreaterThan(String value) {
            addCriterion("CARD_DOC_PURP >", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_PURP >=", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpLessThan(String value) {
            addCriterion("CARD_DOC_PURP <", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpLessThanOrEqualTo(String value) {
            addCriterion("CARD_DOC_PURP <=", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpLike(String value) {
            addCriterion("CARD_DOC_PURP like", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpNotLike(String value) {
            addCriterion("CARD_DOC_PURP not like", value, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpIn(List values) {
            addCriterion("CARD_DOC_PURP in", values, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpNotIn(List values) {
            addCriterion("CARD_DOC_PURP not in", values, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpBetween(String value1, String value2) {
            addCriterion("CARD_DOC_PURP between", value1, value2, "cardDocPurp");
            return (Criteria) this;
        }

        public Criteria andCardDocPurpNotBetween(String value1, String value2) {
            addCriterion("CARD_DOC_PURP not between", value1, value2, "cardDocPurp");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 05 09:27:36 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DTRUN1.ZC_FA_CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}