package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ZcFaCardSubExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    protected List oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public ZcFaCardSubExample() {
        oredCriteria = new ArrayList();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public List getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List getAllCriteria() {
            return criteria;
        }

        public List getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List dateList = new ArrayList();
            Iterator iter = values.iterator();
            while (iter.hasNext()) {
//                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCardSubCodeIsNull() {
            addCriterion("CARD_SUB_CODE is null");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeIsNotNull() {
            addCriterion("CARD_SUB_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeEqualTo(String value) {
            addCriterion("CARD_SUB_CODE =", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeNotEqualTo(String value) {
            addCriterion("CARD_SUB_CODE <>", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeGreaterThan(String value) {
            addCriterion("CARD_SUB_CODE >", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_SUB_CODE >=", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeLessThan(String value) {
            addCriterion("CARD_SUB_CODE <", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeLessThanOrEqualTo(String value) {
            addCriterion("CARD_SUB_CODE <=", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeLike(String value) {
            addCriterion("CARD_SUB_CODE like", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeNotLike(String value) {
            addCriterion("CARD_SUB_CODE not like", value, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeIn(List values) {
            addCriterion("CARD_SUB_CODE in", values, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeNotIn(List values) {
            addCriterion("CARD_SUB_CODE not in", values, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeBetween(String value1, String value2) {
            addCriterion("CARD_SUB_CODE between", value1, value2, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardSubCodeNotBetween(String value1, String value2) {
            addCriterion("CARD_SUB_CODE not between", value1, value2, "cardSubCode");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNull() {
            addCriterion("CARD_ID is null");
            return (Criteria) this;
        }

        public Criteria andCardIdIsNotNull() {
            addCriterion("CARD_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCardIdEqualTo(String value) {
            addCriterion("CARD_ID =", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotEqualTo(String value) {
            addCriterion("CARD_ID <>", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThan(String value) {
            addCriterion("CARD_ID >", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdGreaterThanOrEqualTo(String value) {
            addCriterion("CARD_ID >=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThan(String value) {
            addCriterion("CARD_ID <", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLessThanOrEqualTo(String value) {
            addCriterion("CARD_ID <=", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdLike(String value) {
            addCriterion("CARD_ID like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotLike(String value) {
            addCriterion("CARD_ID not like", value, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdIn(List values) {
            addCriterion("CARD_ID in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotIn(List values) {
            addCriterion("CARD_ID not in", values, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdBetween(String value1, String value2) {
            addCriterion("CARD_ID between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andCardIdNotBetween(String value1, String value2) {
            addCriterion("CARD_ID not between", value1, value2, "cardId");
            return (Criteria) this;
        }

        public Criteria andFaSubNameIsNull() {
            addCriterion("FA_SUB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andFaSubNameIsNotNull() {
            addCriterion("FA_SUB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubNameEqualTo(String value) {
            addCriterion("FA_SUB_NAME =", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameNotEqualTo(String value) {
            addCriterion("FA_SUB_NAME <>", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameGreaterThan(String value) {
            addCriterion("FA_SUB_NAME >", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameGreaterThanOrEqualTo(String value) {
            addCriterion("FA_SUB_NAME >=", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameLessThan(String value) {
            addCriterion("FA_SUB_NAME <", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameLessThanOrEqualTo(String value) {
            addCriterion("FA_SUB_NAME <=", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameLike(String value) {
            addCriterion("FA_SUB_NAME like", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameNotLike(String value) {
            addCriterion("FA_SUB_NAME not like", value, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameIn(List values) {
            addCriterion("FA_SUB_NAME in", values, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameNotIn(List values) {
            addCriterion("FA_SUB_NAME not in", values, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameBetween(String value1, String value2) {
            addCriterion("FA_SUB_NAME between", value1, value2, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNameNotBetween(String value1, String value2) {
            addCriterion("FA_SUB_NAME not between", value1, value2, "faSubName");
            return (Criteria) this;
        }

        public Criteria andFaSubNumIsNull() {
            addCriterion("FA_SUB_NUM is null");
            return (Criteria) this;
        }

        public Criteria andFaSubNumIsNotNull() {
            addCriterion("FA_SUB_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubNumEqualTo(Long value) {
            addCriterion("FA_SUB_NUM =", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumNotEqualTo(Long value) {
            addCriterion("FA_SUB_NUM <>", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumGreaterThan(Long value) {
            addCriterion("FA_SUB_NUM >", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumGreaterThanOrEqualTo(Long value) {
            addCriterion("FA_SUB_NUM >=", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumLessThan(Long value) {
            addCriterion("FA_SUB_NUM <", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumLessThanOrEqualTo(Long value) {
            addCriterion("FA_SUB_NUM <=", value, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumIn(List values) {
            addCriterion("FA_SUB_NUM in", values, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumNotIn(List values) {
            addCriterion("FA_SUB_NUM not in", values, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumBetween(Long value1, Long value2) {
            addCriterion("FA_SUB_NUM between", value1, value2, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubNumNotBetween(Long value1, Long value2) {
            addCriterion("FA_SUB_NUM not between", value1, value2, "faSubNum");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceIsNull() {
            addCriterion("FA_SUB_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceIsNotNull() {
            addCriterion("FA_SUB_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceEqualTo(BigDecimal value) {
            addCriterion("FA_SUB_PRICE =", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceNotEqualTo(BigDecimal value) {
            addCriterion("FA_SUB_PRICE <>", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceGreaterThan(BigDecimal value) {
            addCriterion("FA_SUB_PRICE >", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("FA_SUB_PRICE >=", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceLessThan(BigDecimal value) {
            addCriterion("FA_SUB_PRICE <", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("FA_SUB_PRICE <=", value, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceIn(List values) {
            addCriterion("FA_SUB_PRICE in", values, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceNotIn(List values) {
            addCriterion("FA_SUB_PRICE not in", values, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FA_SUB_PRICE between", value1, value2, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("FA_SUB_PRICE not between", value1, value2, "faSubPrice");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecIsNull() {
            addCriterion("FA_SUB_SPEC is null");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecIsNotNull() {
            addCriterion("FA_SUB_SPEC is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecEqualTo(String value) {
            addCriterion("FA_SUB_SPEC =", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecNotEqualTo(String value) {
            addCriterion("FA_SUB_SPEC <>", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecGreaterThan(String value) {
            addCriterion("FA_SUB_SPEC >", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecGreaterThanOrEqualTo(String value) {
            addCriterion("FA_SUB_SPEC >=", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecLessThan(String value) {
            addCriterion("FA_SUB_SPEC <", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecLessThanOrEqualTo(String value) {
            addCriterion("FA_SUB_SPEC <=", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecLike(String value) {
            addCriterion("FA_SUB_SPEC like", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecNotLike(String value) {
            addCriterion("FA_SUB_SPEC not like", value, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecIn(List values) {
            addCriterion("FA_SUB_SPEC in", values, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecNotIn(List values) {
            addCriterion("FA_SUB_SPEC not in", values, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecBetween(String value1, String value2) {
            addCriterion("FA_SUB_SPEC between", value1, value2, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubSpecNotBetween(String value1, String value2) {
            addCriterion("FA_SUB_SPEC not between", value1, value2, "faSubSpec");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpIsNull() {
            addCriterion("FA_SUB_PURP is null");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpIsNotNull() {
            addCriterion("FA_SUB_PURP is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpEqualTo(String value) {
            addCriterion("FA_SUB_PURP =", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpNotEqualTo(String value) {
            addCriterion("FA_SUB_PURP <>", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpGreaterThan(String value) {
            addCriterion("FA_SUB_PURP >", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpGreaterThanOrEqualTo(String value) {
            addCriterion("FA_SUB_PURP >=", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpLessThan(String value) {
            addCriterion("FA_SUB_PURP <", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpLessThanOrEqualTo(String value) {
            addCriterion("FA_SUB_PURP <=", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpLike(String value) {
            addCriterion("FA_SUB_PURP like", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpNotLike(String value) {
            addCriterion("FA_SUB_PURP not like", value, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpIn(List values) {
            addCriterion("FA_SUB_PURP in", values, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpNotIn(List values) {
            addCriterion("FA_SUB_PURP not in", values, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpBetween(String value1, String value2) {
            addCriterion("FA_SUB_PURP between", value1, value2, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubPurpNotBetween(String value1, String value2) {
            addCriterion("FA_SUB_PURP not between", value1, value2, "faSubPurp");
            return (Criteria) this;
        }

        public Criteria andFaSubDateIsNull() {
            addCriterion("FA_SUB_DATE is null");
            return (Criteria) this;
        }

        public Criteria andFaSubDateIsNotNull() {
            addCriterion("FA_SUB_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubDateEqualTo(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE =", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE <>", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateGreaterThan(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE >", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE >=", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateLessThan(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE <", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FA_SUB_DATE <=", value, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateIn(List values) {
            addCriterionForJDBCDate("FA_SUB_DATE in", values, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateNotIn(List values) {
            addCriterionForJDBCDate("FA_SUB_DATE not in", values, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FA_SUB_DATE between", value1, value2, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FA_SUB_DATE not between", value1, value2, "faSubDate");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeIsNull() {
            addCriterion("FA_SUB_CODE is null");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeIsNotNull() {
            addCriterion("FA_SUB_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeEqualTo(String value) {
            addCriterion("FA_SUB_CODE =", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeNotEqualTo(String value) {
            addCriterion("FA_SUB_CODE <>", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeGreaterThan(String value) {
            addCriterion("FA_SUB_CODE >", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeGreaterThanOrEqualTo(String value) {
            addCriterion("FA_SUB_CODE >=", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeLessThan(String value) {
            addCriterion("FA_SUB_CODE <", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeLessThanOrEqualTo(String value) {
            addCriterion("FA_SUB_CODE <=", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeLike(String value) {
            addCriterion("FA_SUB_CODE like", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeNotLike(String value) {
            addCriterion("FA_SUB_CODE not like", value, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeIn(List values) {
            addCriterion("FA_SUB_CODE in", values, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeNotIn(List values) {
            addCriterion("FA_SUB_CODE not in", values, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeBetween(String value1, String value2) {
            addCriterion("FA_SUB_CODE between", value1, value2, "faSubCode");
            return (Criteria) this;
        }

        public Criteria andFaSubCodeNotBetween(String value1, String value2) {
            addCriterion("FA_SUB_CODE not between", value1, value2, "faSubCode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 05 09:34:34 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ZC_FA_CARD_SUB
     *
     * @mbggenerated Wed Mar 05 09:34:34 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}