package com.ufgov.zc.common.sf.model;

import java.math.BigDecimal;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class ZcFaUsing extends ZcBaseBill{
    /**
   * 
   */
  private static final long serialVersionUID = 3724127456711001508L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.ORG_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.USE_RAT
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private BigDecimal useRat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.SERIAL
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.USE_EMP_NAME
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String useEmpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.ND
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private Integer nd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.CO_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String coCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZC_FA_USING.USE_EMP_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    private String useEmpCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.CARD_ID
     *
     * @return the value of ZC_FA_USING.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.CARD_ID
     *
     * @param cardId the value for ZC_FA_USING.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.ORG_CODE
     *
     * @return the value of ZC_FA_USING.ORG_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.ORG_CODE
     *
     * @param orgCode the value for ZC_FA_USING.ORG_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.USE_RAT
     *
     * @return the value of ZC_FA_USING.USE_RAT
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public BigDecimal getUseRat() {
        return useRat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.USE_RAT
     *
     * @param useRat the value for ZC_FA_USING.USE_RAT
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setUseRat(BigDecimal useRat) {
        this.useRat = useRat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.SERIAL
     *
     * @return the value of ZC_FA_USING.SERIAL
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.SERIAL
     *
     * @param serial the value for ZC_FA_USING.SERIAL
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setSerial(String serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.USE_EMP_NAME
     *
     * @return the value of ZC_FA_USING.USE_EMP_NAME
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getUseEmpName() {
        return useEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.USE_EMP_NAME
     *
     * @param useEmpName the value for ZC_FA_USING.USE_EMP_NAME
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setUseEmpName(String useEmpName) {
        this.useEmpName = useEmpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.ND
     *
     * @return the value of ZC_FA_USING.ND
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public Integer getNd() {
        return nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.ND
     *
     * @param nd the value for ZC_FA_USING.ND
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setNd(Integer nd) {
        this.nd = nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.CO_CODE
     *
     * @return the value of ZC_FA_USING.CO_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getCoCode() {
        return coCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.CO_CODE
     *
     * @param coCode the value for ZC_FA_USING.CO_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setCoCode(String coCode) {
        this.coCode = coCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZC_FA_USING.USE_EMP_CODE
     *
     * @return the value of ZC_FA_USING.USE_EMP_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public String getUseEmpCode() {
        return useEmpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZC_FA_USING.USE_EMP_CODE
     *
     * @param useEmpCode the value for ZC_FA_USING.USE_EMP_CODE
     *
     * @mbggenerated Wed Mar 05 09:37:00 CST 2014
     */
    public void setUseEmpCode(String useEmpCode) {
        this.useEmpCode = useEmpCode;
    }
}