package com.ufgov.zc.common.sf.model;

import com.ufgov.zc.common.zc.model.ZcBaseBill;

public class ZcFaCardDoc extends ZcBaseBill{
    /**
   * 
   */
  private static final long serialVersionUID = 4237885306580106420L;

  private String tempId;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTRUN1.ZC_FA_CARD_DOC.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    private String cardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_LIST
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    private String cardDocList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    private String cardDoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_BLOBID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    private String cardDocBlobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_PURP
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    private String cardDocPurp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_ID
     *
     * @return the value of DTRUN1.ZC_FA_CARD_DOC.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_ID
     *
     * @param cardId the value for DTRUN1.ZC_FA_CARD_DOC.CARD_ID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_LIST
     *
     * @return the value of DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_LIST
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getCardDocList() {
        return cardDocList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_LIST
     *
     * @param cardDocList the value for DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_LIST
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setCardDocList(String cardDocList) {
        this.cardDocList = cardDocList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC
     *
     * @return the value of DTRUN1.ZC_FA_CARD_DOC.CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getCardDoc() {
        return cardDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC
     *
     * @param cardDoc the value for DTRUN1.ZC_FA_CARD_DOC.CARD_DOC
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setCardDoc(String cardDoc) {
        this.cardDoc = cardDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_BLOBID
     *
     * @return the value of DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_BLOBID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getCardDocBlobid() {
        return cardDocBlobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_BLOBID
     *
     * @param cardDocBlobid the value for DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_BLOBID
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setCardDocBlobid(String cardDocBlobid) {
        this.cardDocBlobid = cardDocBlobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_PURP
     *
     * @return the value of DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_PURP
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public String getCardDocPurp() {
        return cardDocPurp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_PURP
     *
     * @param cardDocPurp the value for DTRUN1.ZC_FA_CARD_DOC.CARD_DOC_PURP
     *
     * @mbggenerated Wed Mar 05 09:27:36 CST 2014
     */
    public void setCardDocPurp(String cardDocPurp) {
        this.cardDocPurp = cardDocPurp;
    }

    public String getTempId() {
      return tempId;
    }

    public void setTempId(String tempId) {
      this.tempId = tempId;
    }
}